# Generated by Django 2.2.2 on 2019-07-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_vendas_quantidade_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='nome_venda',
        ),
    ]
